controller:
  hero_chassis_controller:
    type: hero_chassis_controller/HeroChassisController
    pid1: { p: 5000.0, i: 100, d: 5.0 }
    pid2: { p: 5000.0, i: 100, d: 5.0 }
    pid3: { p: 5000.0, i: 100, d: 5.0 }
    pid4: { p: 5000.0, i: 100, d: 5.0 }
    Wheel_track: 0.410
    Wheel_base: 0.320
    Odom_mode: true

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50