controller:
  simple_chassis_controller:
    type: simple_chassis_controller/SimpleChassisController

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  pid1: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0}
  pid2: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0}
  pid3: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0}
  pid4: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0}

wheel_track : 0.410
wheel_base: 0.320
wheel_radius: 0.02
